name: nearby_chat
description: Offline P2P messaging with WhatsApp-like UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  flutter_p2p_connection: any
  nearby_connections: any
  permission_handler: any
  flutter_bloc: any
  equatable: any
  get_it: any
  injectable: any
  go_router: any
  hive: any
  hive_flutter: any
  drift: any
  sqlite3_flutter_libs: any
  flutter_secure_storage: any
  path_provider: any
  encrypt: any
  pointycastle: any
  crypto: any
  cached_network_image: any
  lottie: any
  shimmer: any
  photo_view: any
  intl: any
  flutter_svg: any
  uuid: any
  qr_flutter: any
  share_plus: any
  logger: any
  dartz: any
  freezed_annotation: any
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  hive_generator: any
  drift_dev: any
  injectable_generator: any
  freezed: any
  json_serializable: any
  mockito: any
  bloc_test: any

dependency_overrides:
  mime: any

flutter:
  uses-material-design: true
